//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_ProjectAssignment_SP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DemoEntities : DbContext
    {
        public DemoEntities()
            : base("name=DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<V_DEV_ProductType> V_DEV_ProductType { get; set; }
        public virtual DbSet<V_MST_Brand> V_MST_Brand { get; set; }
        public virtual DbSet<V_MST_Category> V_MST_Category { get; set; }
        public virtual DbSet<V_MST_Product> V_MST_Product { get; set; }
        public virtual DbSet<V_MST_ProductSpecification> V_MST_ProductSpecification { get; set; }
        public virtual DbSet<Table_1> Table_1 { get; set; }
    
        public virtual int USP_InsertProductRecords(string productcode, string productName, string productdescription, string producttype, string brandIds, string categoryids, string xmlstring)
        {
            var productcodeParameter = productcode != null ?
                new ObjectParameter("productcode", productcode) :
                new ObjectParameter("productcode", typeof(string));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productdescriptionParameter = productdescription != null ?
                new ObjectParameter("productdescription", productdescription) :
                new ObjectParameter("productdescription", typeof(string));
    
            var producttypeParameter = producttype != null ?
                new ObjectParameter("producttype", producttype) :
                new ObjectParameter("producttype", typeof(string));
    
            var brandIdsParameter = brandIds != null ?
                new ObjectParameter("BrandIds", brandIds) :
                new ObjectParameter("BrandIds", typeof(string));
    
            var categoryidsParameter = categoryids != null ?
                new ObjectParameter("categoryids", categoryids) :
                new ObjectParameter("categoryids", typeof(string));
    
            var xmlstringParameter = xmlstring != null ?
                new ObjectParameter("xmlstring", xmlstring) :
                new ObjectParameter("xmlstring", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_InsertProductRecords", productcodeParameter, productNameParameter, productdescriptionParameter, producttypeParameter, brandIdsParameter, categoryidsParameter, xmlstringParameter);
        }
    
        public virtual ObjectResult<USP_SearchProductRecords_Result> USP_SearchProductRecords(string productname, string productcode, string brandid, string categoryid, string producttype)
        {
            var productnameParameter = productname != null ?
                new ObjectParameter("productname", productname) :
                new ObjectParameter("productname", typeof(string));
    
            var productcodeParameter = productcode != null ?
                new ObjectParameter("productcode", productcode) :
                new ObjectParameter("productcode", typeof(string));
    
            var brandidParameter = brandid != null ?
                new ObjectParameter("brandid", brandid) :
                new ObjectParameter("brandid", typeof(string));
    
            var categoryidParameter = categoryid != null ?
                new ObjectParameter("categoryid", categoryid) :
                new ObjectParameter("categoryid", typeof(string));
    
            var producttypeParameter = producttype != null ?
                new ObjectParameter("producttype", producttype) :
                new ObjectParameter("producttype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SearchProductRecords_Result>("USP_SearchProductRecords", productnameParameter, productcodeParameter, brandidParameter, categoryidParameter, producttypeParameter);
        }
    
        public virtual int USP_UpdateProductRecords(Nullable<int> productCode, string productName, string productdescription, string producttype, string brandIds, string categoryids, string xmlstring)
        {
            var productCodeParameter = productCode.HasValue ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(int));
    
            var productNameParameter = productName != null ?
                new ObjectParameter("ProductName", productName) :
                new ObjectParameter("ProductName", typeof(string));
    
            var productdescriptionParameter = productdescription != null ?
                new ObjectParameter("productdescription", productdescription) :
                new ObjectParameter("productdescription", typeof(string));
    
            var producttypeParameter = producttype != null ?
                new ObjectParameter("producttype", producttype) :
                new ObjectParameter("producttype", typeof(string));
    
            var brandIdsParameter = brandIds != null ?
                new ObjectParameter("BrandIds", brandIds) :
                new ObjectParameter("BrandIds", typeof(string));
    
            var categoryidsParameter = categoryids != null ?
                new ObjectParameter("categoryids", categoryids) :
                new ObjectParameter("categoryids", typeof(string));
    
            var xmlstringParameter = xmlstring != null ?
                new ObjectParameter("xmlstring", xmlstring) :
                new ObjectParameter("xmlstring", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UpdateProductRecords", productCodeParameter, productNameParameter, productdescriptionParameter, producttypeParameter, brandIdsParameter, categoryidsParameter, xmlstringParameter);
        }
    }
}
